const {chromium}=require('/Users/gorkanelson/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const fs=require('fs'),path=require('path'),assert=require('assert'),crypto=require('crypto');
(async()=>{const b=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--allow-file-access-from-files']});const p=await b.newPage({viewport:{width:1500,height:1000}});const errors=[],checks=[];let loads=0;p.on('pageerror',e=>errors.push(e.message));p.on('load',()=>loads++);await p.goto('file://'+path.resolve('VILLA_MANUELA_VISOR_DEFINITIVO-v112.html'));await p.waitForFunction(()=>window.__villaReady===true,{timeout:60000});
const state=()=>p.evaluate(()=>villaViewer.state);const audit=()=>p.evaluate(()=>villaViewer.audit());const eq=(a,b)=>assert.deepStrictEqual(a,b);
async function click(id){const before=await state();await p.locator('#'+id).click();const after=await state();eq(before.camera,after.camera);checks.push(id+' conserva cámara');assert.equal((await audit()).glError,0);}
async function snap(n){await p.locator('#view').screenshot({path:'auxiliar-visor-definitivo/'+n+'.png'});const a=await audit();delete a.sourceIndices;checks.push({n,a});console.log(n);}
await p.evaluate(()=>__v106View([27,-27,23],[0,-3,2],'all'));const camera=(await state()).camera;
await snap('01_reformada_dia_entorno');const day=await p.locator('#view').screenshot();
await click('lightingB');await snap('03_reformada_noche_entorno');await click('lightingA');eq(await p.locator('#view').screenshot(),day);checks.push('Día recuperado píxel a píxel');
await click('scopeB');assert.equal((await audit()).externalVisible,0);await snap('02_reformada_dia_parcela');await click('lightingB');await snap('04_reformada_noche_parcela');await click('lightingA');await click('scopeA');eq(await p.locator('#view').screenshot(),day);
await click('versionA');await snap('05_actual_dia_entorno');const actual=(await audit()).sourceIndices;await click('versionB');await click('versionA');eq((await audit()).sourceIndices,actual);await click('scopeB');await snap('06_actual_parcela');assert.equal((await audit()).externalVisible,0);await click('versionB');
for(const level of [3,0,1,2,4]){const el=p.locator('[data-level="'+level+'"]');const before=await state();await el.uncheck();const a=await audit();assert.equal(a.levels[level],0);eq(a.state.camera,before.camera);await snap('planta_oculta_'+level);await el.check();}
await p.click('#separateToggle');for(const val of ['3','6','0']){await p.locator('#explode').fill(val);await p.locator('#explode').dispatchEvent('input');eq((await state()).camera,camera);await snap('separacion_'+val);}
await p.locator('#explode').fill('3');await p.locator('#explode').dispatchEvent('input');await p.click('#separateClose');assert.equal((await state()).separation,0);
await p.locator('[data-level="1"]').uncheck();await snap('08_parcela_sin_P1');await p.locator('[data-level="1"]').check();
for(const side of ['N','S','E','O']){await p.locator('#facade'+side).uncheck();await snap('fachada_oculta_'+side);await p.click('#restoreFacades');}
await click('lightingB');await p.locator('#facadeO').uncheck();await snap('09_noche_sin_O');await click('lightingA');await p.click('#restoreFacades');await p.selectOption('#mode','2');await p.locator('[data-level="4"]').uncheck();await p.locator('#facadeN').uncheck();await snap('10_P2_sin_CUB_N');
// Independence under combined, non-default state.
const before=await state();await click('versionA');await click('lightingB');await click('scopeA');const combined=await state();for(const k of ['visibleFloors','hiddenFacades','separation','mode','terrainVisible','furnitureVisible','contoursVisible','camera'])eq(combined[k],before[k]);await click('versionB');await click('lightingA');await click('scopeB');eq(await state(),before);
await p.click('#imageOrientation');assert.equal((await state()).camera.imageOrientation,'vertical');await p.click('#imageOrientation');await p.selectOption('#focalMM','35');assert.equal((await state()).camera.focalMM,35);await p.click('#heightPlus');assert.equal((await state()).camera.cameraHeight,1.66);await p.click('#heightReset');assert.equal((await state()).camera.cameraHeight,1.65);await p.click('#cleanCapture');assert.equal(await p.locator('#viewportStage').getAttribute('data-clean'),'true');await p.click('#cleanCapture');await p.click('#fullscreen');await p.waitForTimeout(150);assert(await p.evaluate(()=>!!document.fullscreenElement));await p.evaluate(()=>document.exitFullscreen());
for(const id of ['cameraName','cameraKind','cameraSave','cameraList','cameraFrame','cameraExport','cameraImport','exteriorViews','interiorViews','parkingGate'])assert.equal(await p.locator('#'+id).count(),0);
const conflicts=await p.evaluate(()=>__viewerRuntimeData().conflicts);fs.writeFileSync('auxiliar-visor-definitivo/mallas_multiplanta.json',JSON.stringify(conflicts,null,2));eq(errors,[]);assert.equal(loads,1);fs.writeFileSync('auxiliar-visor-definitivo/VALIDACION.json',JSON.stringify({checks,errors,loads,conflicts:conflicts.length,passed:true},null,2));console.log('PASSED',checks.length);await b.close();})().catch(e=>{console.error(e);process.exit(1)});
